/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuthRouteImport } from './routes/admin._auth'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'
import { Route as AdminAuthConfiguracoesRouteImport } from './routes/admin._auth.configuracoes'
import { Route as AdminAuthDashboardRouteImport } from './routes/admin._auth.dashboard'
import { Route as AdminAuthImoveisIndexRouteImport } from './routes/admin._auth.imoveis.index'
import { Route as AdminAuthImoveisNovoRouteImport } from './routes/admin._auth.imoveis.novo'
import { Route as AdminAuthImoveisIdEditarRouteImport } from './routes/admin._auth.imoveis.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/_auth',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/imoveis/$slug',
  path: '/imoveis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthConfiguracoesRoute = AdminAuthConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthDashboardRoute = AdminAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthImoveisIndexRoute = AdminAuthImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthImoveisNovoRoute = AdminAuthImoveisNovoRouteImport.update({
  id: '/imoveis/novo',
  path: '/imoveis/novo',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthImoveisIdEditarRoute =
  AdminAuthImoveisIdEditarRouteImport.update({
    id: '/imoveis/$id/editar',
    path: '/imoveis/$id/editar',
    getParentRoute: () => AdminAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/admin/configuracoes': typeof AdminAuthConfiguracoesRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/imoveis/novo': typeof AdminAuthImoveisNovoRoute
  '/admin/imoveis/': typeof AdminAuthImoveisIndexRoute
  '/admin/imoveis/$id/editar': typeof AdminAuthImoveisIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/admin/configuracoes': typeof AdminAuthConfiguracoesRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/imoveis/novo': typeof AdminAuthImoveisNovoRoute
  '/admin/imoveis': typeof AdminAuthImoveisIndexRoute
  '/admin/imoveis/$id/editar': typeof AdminAuthImoveisIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/admin/_auth/configuracoes': typeof AdminAuthConfiguracoesRoute
  '/admin/_auth/dashboard': typeof AdminAuthDashboardRoute
  '/admin/_auth/imoveis/novo': typeof AdminAuthImoveisNovoRoute
  '/admin/_auth/imoveis/': typeof AdminAuthImoveisIndexRoute
  '/admin/_auth/imoveis/$id/editar': typeof AdminAuthImoveisIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/admin'
    | '/admin/login'
    | '/imoveis/$slug'
    | '/admin/'
    | '/imoveis/'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/imoveis/novo'
    | '/admin/imoveis/'
    | '/admin/imoveis/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/admin'
    | '/admin/login'
    | '/imoveis/$slug'
    | '/imoveis'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/imoveis/novo'
    | '/admin/imoveis'
    | '/admin/imoveis/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/admin/_auth'
    | '/admin/login'
    | '/imoveis/$slug'
    | '/admin/'
    | '/imoveis/'
    | '/admin/_auth/configuracoes'
    | '/admin/_auth/dashboard'
    | '/admin/_auth/imoveis/novo'
    | '/admin/_auth/imoveis/'
    | '/admin/_auth/imoveis/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/imoveis/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/configuracoes': {
      id: '/admin/_auth/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAuthConfiguracoesRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dashboard': {
      id: '/admin/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthDashboardRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/imoveis/': {
      id: '/admin/_auth/imoveis/'
      path: '/imoveis'
      fullPath: '/admin/imoveis/'
      preLoaderRoute: typeof AdminAuthImoveisIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/imoveis/novo': {
      id: '/admin/_auth/imoveis/novo'
      path: '/imoveis/novo'
      fullPath: '/admin/imoveis/novo'
      preLoaderRoute: typeof AdminAuthImoveisNovoRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/imoveis/$id/editar': {
      id: '/admin/_auth/imoveis/$id/editar'
      path: '/imoveis/$id/editar'
      fullPath: '/admin/imoveis/$id/editar'
      preLoaderRoute: typeof AdminAuthImoveisIdEditarRouteImport
      parentRoute: typeof AdminAuthRoute
    }
  }
}

interface AdminAuthRouteChildren {
  AdminAuthConfiguracoesRoute: typeof AdminAuthConfiguracoesRoute
  AdminAuthDashboardRoute: typeof AdminAuthDashboardRoute
  AdminAuthImoveisNovoRoute: typeof AdminAuthImoveisNovoRoute
  AdminAuthImoveisIndexRoute: typeof AdminAuthImoveisIndexRoute
  AdminAuthImoveisIdEditarRoute: typeof AdminAuthImoveisIdEditarRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthConfiguracoesRoute: AdminAuthConfiguracoesRoute,
  AdminAuthDashboardRoute: AdminAuthDashboardRoute,
  AdminAuthImoveisNovoRoute: AdminAuthImoveisNovoRoute,
  AdminAuthImoveisIndexRoute: AdminAuthImoveisIndexRoute,
  AdminAuthImoveisIdEditarRoute: AdminAuthImoveisIdEditarRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ImoveisSlugRoute: ImoveisSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
