/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuthRouteImport } from './routes/admin._auth'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/_auth',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/imoveis/$slug',
  path: '/imoveis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/admin': typeof AdminAuthRoute
  '/admin/login': typeof AdminLoginRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/imoveis': typeof ImoveisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/admin/_auth': typeof AdminAuthRoute
  '/admin/login': typeof AdminLoginRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/admin'
    | '/admin/login'
    | '/imoveis/$slug'
    | '/admin/'
    | '/imoveis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/contato' | '/admin' | '/admin/login' | '/imoveis/$slug' | '/imoveis'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/admin/_auth'
    | '/admin/login'
    | '/imoveis/$slug'
    | '/admin/'
    | '/imoveis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/imoveis/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  AdminAuthRoute: AdminAuthRoute,
  AdminLoginRoute: AdminLoginRoute,
  ImoveisSlugRoute: ImoveisSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
